require: rubocop-rails

Style/Documentation:
  Exclude:
    - 'test/test_helper.rb'
    - 'test/application_system_test_case.rb'
    - 'config/application.rb'
    - 'app/models/application_record.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/helpers/application_helper.rb'

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - 'config/environments/production.rb'

Layout/SpaceInsidePercentLiteralDelimiters:
  Exclude:
    - 'Gemfile'

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/channels/application_cable/connection_test.rb'
    - 'test/test_helper.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'test/test_helper.rb'
    - 'test/channels/application_cable/connection_test.rb'
    - 'test/application_system_test_case.rb'
    - 'db/seeds.rb'
    - 'config/**/*'
    - 'config.ru'
    - 'app/models/application_record.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/jobs/application_job.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/controllers/application_controller.rb'
    - 'app/channels/**/*'
    - 'Rakefile'
    - 'Gemfile'

Style/GlobalStdStream:
  Exclude:
    - 'config/environments/production.rb'

Style/RedundantFetchBlock:
  Exclude:
    - 'config/puma.rb'

Style/StringLiterals:
  Exclude:
    - 'test/**/*'
    - 'config/**/*'
    - 'config.ru'
    - 'app/mailers/**/*'
    - 'Rakefile'
    - 'Gemfile'

Style/SymbolArray:
  EnforcedStyle: percent
  MinSize: 10
